prostage_accueil:
    path: /accueil
    controller: App\Controller\ProstageController::index

prostage_formations:
    path: /formations
    controller: App\Controller\ProstageController::formations

prostage_entreprises:
    path: /entreprises
    controller: App\Controller\ProstageController::entreprises

prostage_stages:
    path: /stages/{id}
    controller: App\Controller\ProstageController::stages

prostage_stagesParEntreprise:
    path: /entreprises/{id_entreprise}
    controller: App\Controller\ProstageController::stagesParEntreprise

prostage_stagesParFormation:
    path: /formations/{id_formation}
    controller: App\Controller\ProstageController::stagesParFormation